services:
  nginx-proxy:
    build: backend/nginx
    restart: always
    volumes:
      - ./backend/nginx/default.conf:/tmp/default.conf
    env_file:
      - 'backend-urls.env'
    environment: 
      - FLASK_SERVER_ADDR=flask-backend:8000
      - SVELTE_FRONT_ADDR=svelte-frontend:3000
    ports:
      - "80:80"
    depends_on:
      - flask-backend
      - svelte-frontend
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: /app/start.sh

  flask-backend:
    build: backend/flask
    env_file:
      - 'backend-urls.env'
    volumes:
      - posts-storage:/data
    ports: 
      - '8080:8080'
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8000/flask-health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:8000 app:app

  svelte-frontend:
    build: frontend
    ports: 
      - '3001:3001'
    env_file:
      - 'backend-urls.env'
    environment:
      - FLASK_SERVER_ADDR=flask-backend:8000
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 3
    command: node build

volumes:
  posts-storage:
    driver_opts:
      type: none
      o: bind
      device: /data