version: '3.8'

services:
  svelte-frontend:
    build:
      context: frontend
      target: development  # Use the development stage
    volumes:
      - $PWD/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3001:3001'
    command: nodemon --watch src --watch static --ignore node_modules --ignore build --ignore .git --ignore tmp --exec npm run dev -- --port=3001

volumes:
  posts-storage:
    driver_opts:
      type: none
      o: bind
      device: /data